import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/custom/Navbar/NavBar";
import Footer from "@/components/custom/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
